# Single Hydra config file for FlowGRPO tutorial

# Hydra configuration for output directory structure
hydra:
  job:
    name: train  # This creates outputs0/train/YYYY-MM-DD/HH-MM-SS/ structure

# Run name for logging and outputs
run_name: "flowgrpo"

# Random seed for reproducibility
seed: 42

# Model architecture hyperparameters
model:
  signal_dim: 784  # MNIST: 28x28 = 784
  prompt_dim: 32
  hidden_dim: 256  # Increased for MNIST complexity
  vocab_size: 10   # Digits 0-9
  sigma_max: 80.0  # Maximum noise level for flow matching (sigma = t * sigma_max)

# Training hyperparameters
training:
  max_steps: 100000  # Maximum number of training steps
  batch_size: 4
  num_samples_per_label: 4
  num_steps: 20  # Number of flow matching steps per sample
  eval_num_steps: 20  # Number of flow matching steps for evaluation
  lr: 1e-4
  clip_range: 0.0001
  beta: 0.0
  eval_freq: 500  # Frequency of evaluation (in steps)
  max_grad_norm: 1.0
  max_log_diff: 10.0  # Maximum log probability difference for numerical stability (prevents exp overflow)
  adv_clip_max: 5.0  # Maximum absolute value for advantages (clipping)
  num_inner_epochs: 1  # Number of inner epochs to train on each batch of samples
  device: "auto"  # Options: "cpu", "cuda", "auto" (auto-detect)
  save_freq: 1000  # Frequency of checkpoint saving (in steps)

# Checkpoint configuration
pretrained_checkpoint: "./outputs/2026-01-15/22-22-15/checkpoints/iter_001000.pt"  # Path to pretrained checkpoint
resume_from: null  # Path to checkpoint to resume training from (loads optimizer state too)

# Reward configuration
reward:
  config: "large"  # Reward config: 'large' (default, rewards large/bold digits), 'digit_zero', 'accuracy', 'quality', 'balanced', 'diverse', 'bright', 'centered', 'sparse', 'contrast', 'tiny'

# Dataset configuration
dataset:
  dataset_dir: "dataset"
  split: "train"  # For dataset loading

# Output paths
paths:
  output_dir: "outputs"

# Wandb configuration
wandb:
  enabled: true  # Set to true to enable wandb logging
  project: "minimal-rl"
  run_name: null  # Uses run_name from top level if null
  tags: []  # Optional tags for the run
  log_freq: 10  # Log metrics every N steps (1 = every step)
  log_grad_norm: true  # Whether to log gradient norms (can be expensive)
  num_sample_images: 64  # Number of images to sample for visualization
  num_sampling_steps: 50  # Number of integration steps for sampling
